# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/authpb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/authpb.proto\x12\x06\x61uthDH\"0\n\x0cReqPQRequest\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x11\n\tmessageId\x18\x02 \x01(\x04\"\\\n\rReqPQResponse\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x13\n\x0bserverNonce\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\x04\x12\t\n\x01p\x18\x04 \x01(\t\x12\t\n\x01g\x18\x05 \x01(\x04\"V\n\x12reqDHParamsRequest\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x13\n\x0bserverNonce\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\x04\x12\t\n\x01\x61\x18\x04 \x01(\t\"W\n\x13reqDHParamsResponse\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x13\n\x0bserverNonce\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\x04\x12\t\n\x01\x62\x18\x04 \x01(\t\"(\n\x15IsValidAuthKeyRequest\x12\x0f\n\x07\x61uthkey\x18\x01 \x01(\t\")\n\x16IsValidAuthKeyResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x32\xdc\x01\n\x0b\x41uthService\x12\x34\n\x05reqPQ\x12\x14.authDH.ReqPQRequest\x1a\x15.authDH.ReqPQResponse\x12\x46\n\x0breqDHParams\x12\x1a.authDH.reqDHParamsRequest\x1a\x1b.authDH.reqDHParamsResponse\x12O\n\x0eisValidAuthkey\x12\x1d.authDH.IsValidAuthKeyRequest\x1a\x1e.authDH.IsValidAuthKeyResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.authpb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQPQREQUEST._serialized_start=31
  _REQPQREQUEST._serialized_end=79
  _REQPQRESPONSE._serialized_start=81
  _REQPQRESPONSE._serialized_end=173
  _REQDHPARAMSREQUEST._serialized_start=175
  _REQDHPARAMSREQUEST._serialized_end=261
  _REQDHPARAMSRESPONSE._serialized_start=263
  _REQDHPARAMSRESPONSE._serialized_end=350
  _ISVALIDAUTHKEYREQUEST._serialized_start=352
  _ISVALIDAUTHKEYREQUEST._serialized_end=392
  _ISVALIDAUTHKEYRESPONSE._serialized_start=394
  _ISVALIDAUTHKEYRESPONSE._serialized_end=435
  _AUTHSERVICE._serialized_start=438
  _AUTHSERVICE._serialized_end=658
# @@protoc_insertion_point(module_scope)
