# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import authpb_pb2 as protos_dot_authpb__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reqPQ = channel.unary_unary(
                '/authDH.AuthService/reqPQ',
                request_serializer=protos_dot_authpb__pb2.ReqPQRequest.SerializeToString,
                response_deserializer=protos_dot_authpb__pb2.ReqPQResponse.FromString,
                )
        self.reqDHParams = channel.unary_unary(
                '/authDH.AuthService/reqDHParams',
                request_serializer=protos_dot_authpb__pb2.reqDHParamsRequest.SerializeToString,
                response_deserializer=protos_dot_authpb__pb2.reqDHParamsResponse.FromString,
                )
        self.isValidAuthkey = channel.unary_unary(
                '/authDH.AuthService/isValidAuthkey',
                request_serializer=protos_dot_authpb__pb2.IsValidAuthKeyRequest.SerializeToString,
                response_deserializer=protos_dot_authpb__pb2.IsValidAuthKeyResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reqPQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reqDHParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isValidAuthkey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reqPQ': grpc.unary_unary_rpc_method_handler(
                    servicer.reqPQ,
                    request_deserializer=protos_dot_authpb__pb2.ReqPQRequest.FromString,
                    response_serializer=protos_dot_authpb__pb2.ReqPQResponse.SerializeToString,
            ),
            'reqDHParams': grpc.unary_unary_rpc_method_handler(
                    servicer.reqDHParams,
                    request_deserializer=protos_dot_authpb__pb2.reqDHParamsRequest.FromString,
                    response_serializer=protos_dot_authpb__pb2.reqDHParamsResponse.SerializeToString,
            ),
            'isValidAuthkey': grpc.unary_unary_rpc_method_handler(
                    servicer.isValidAuthkey,
                    request_deserializer=protos_dot_authpb__pb2.IsValidAuthKeyRequest.FromString,
                    response_serializer=protos_dot_authpb__pb2.IsValidAuthKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authDH.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reqPQ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authDH.AuthService/reqPQ',
            protos_dot_authpb__pb2.ReqPQRequest.SerializeToString,
            protos_dot_authpb__pb2.ReqPQResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reqDHParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authDH.AuthService/reqDHParams',
            protos_dot_authpb__pb2.reqDHParamsRequest.SerializeToString,
            protos_dot_authpb__pb2.reqDHParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def isValidAuthkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authDH.AuthService/isValidAuthkey',
            protos_dot_authpb__pb2.IsValidAuthKeyRequest.SerializeToString,
            protos_dot_authpb__pb2.IsValidAuthKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
