# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import sqlpb_pb2 as protos_dot_sqlpb__pb2


class SQLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getUsers = channel.unary_unary(
                '/sqlInjection.SQLService/getUsers',
                request_serializer=protos_dot_sqlpb__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=protos_dot_sqlpb__pb2.GetUsersResponse.FromString,
                )
        self.getUsersWithSqlInject = channel.unary_unary(
                '/sqlInjection.SQLService/getUsersWithSqlInject',
                request_serializer=protos_dot_sqlpb__pb2.GetUsersWithSqlInjectRequest.SerializeToString,
                response_deserializer=protos_dot_sqlpb__pb2.GetUsersResponse.FromString,
                )


class SQLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUsersWithSqlInject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.getUsers,
                    request_deserializer=protos_dot_sqlpb__pb2.GetUsersRequest.FromString,
                    response_serializer=protos_dot_sqlpb__pb2.GetUsersResponse.SerializeToString,
            ),
            'getUsersWithSqlInject': grpc.unary_unary_rpc_method_handler(
                    servicer.getUsersWithSqlInject,
                    request_deserializer=protos_dot_sqlpb__pb2.GetUsersWithSqlInjectRequest.FromString,
                    response_serializer=protos_dot_sqlpb__pb2.GetUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sqlInjection.SQLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SQLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sqlInjection.SQLService/getUsers',
            protos_dot_sqlpb__pb2.GetUsersRequest.SerializeToString,
            protos_dot_sqlpb__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUsersWithSqlInject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sqlInjection.SQLService/getUsersWithSqlInject',
            protos_dot_sqlpb__pb2.GetUsersWithSqlInjectRequest.SerializeToString,
            protos_dot_sqlpb__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
