# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/sqlpb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/sqlpb.proto\x12\x0csqlInjection\"p\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x66\x61mily\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x04\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x04\x12\x1e\n\x03sex\x18\x05 \x01(\x0e\x32\x11.sqlInjection.Sex\x12\x11\n\tcreatedAt\x18\x06 \x01(\t\"U\n\x0fGetUsersRequest\x12\x13\n\x06userId\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x0f\n\x07\x61uthKey\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\x04\x42\t\n\x07_userId\"b\n\x1cGetUsersWithSqlInjectRequest\x12\x13\n\x06userId\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07\x61uthKey\x18\x02 \x01(\t\x12\x11\n\tmessageId\x18\x03 \x01(\x04\x42\t\n\x07_userId\"H\n\x10GetUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.sqlInjection.User\x12\x11\n\tmessageId\x18\x02 \x01(\x04*\x1a\n\x03Sex\x12\x07\n\x03Man\x10\x00\x12\n\n\x06\x46\x65male\x10\x01\x32\xbc\x01\n\nSQLService\x12I\n\x08getUsers\x12\x1d.sqlInjection.GetUsersRequest\x1a\x1e.sqlInjection.GetUsersResponse\x12\x63\n\x15getUsersWithSqlInject\x12*.sqlInjection.GetUsersWithSqlInjectRequest\x1a\x1e.sqlInjection.GetUsersResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.sqlpb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEX._serialized_start=411
  _SEX._serialized_end=437
  _USER._serialized_start=36
  _USER._serialized_end=148
  _GETUSERSREQUEST._serialized_start=150
  _GETUSERSREQUEST._serialized_end=235
  _GETUSERSWITHSQLINJECTREQUEST._serialized_start=237
  _GETUSERSWITHSQLINJECTREQUEST._serialized_end=335
  _GETUSERSRESPONSE._serialized_start=337
  _GETUSERSRESPONSE._serialized_end=409
  _SQLSERVICE._serialized_start=440
  _SQLSERVICE._serialized_end=628
# @@protoc_insertion_point(module_scope)
